### ISSUE TITLE
Don't install in PHP >= 8.0

### ISSUE THREAD

**Issue by quinhone** [melhorenvio/melhor-envio-sdk-php#8]
Don't install in PHP >= 8.0

 [InvalidArgumentException]                                                                                                           
  Package melhorenvio/shipment-sdk-php has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:  
    - melhorenvio/shipment-sdk-php 2.0.0 requires php 7.4.* which does not match your installed version 8.1.0.

**Comment by videfrancisco** [comment]
Yes, same problem here

**Comment by viniciustessmann** [comment]
This issues solved on last version
